# Generated by Django 4.0.3 on 2022-03-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('start_price', models.IntegerField()),
                ('bids_placed', models.IntegerField()),
                ('bidders', models.IntegerField()),
                ('location', models.CharField(max_length=128)),
                ('registered_city', models.CharField(max_length=128)),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(max_length=128)),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('transmission_type', models.CharField(max_length=128)),
                ('fuel_type', models.CharField(max_length=128)),
                ('registration_year', models.IntegerField()),
                ('reference_id', models.CharField(max_length=128)),
            ],
        ),
    ]
