# Generated by Django 4.0.3 on 2022-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfirst', '0002_auction_created_at_auction_updated_at_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
        migrations.AddField(
            model_name='bid',
            name='auction_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
