# Generated by Django 4.0.3 on 2022-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfirst', '0003_remove_bid_auction_bid_auction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
