# Generated by Django 4.0.3 on 2022-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfirst', '0004_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
