version: "3.7"
services:
  db:
    image: "postgres:11.5"
    container_name: "autos_postgres"
    environment:
      POSTGRES_DB: "autos_db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - autos_postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "autos_api"
    env_file: .env
    environment:
      DEBUG: "1"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  autos_postgres_data:
