version: "3.7"
services:
  autos_db:
    image: "postgres:11.5"
    container_name: "autos_postgres"
    environment:
      POSTGRES_DB: "autos_db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - autos_postgres_data:/var/lib/postgresql/data
  autos_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "autos_api"
    env_file: .env
    environment:
      DEBUG: "1"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - autos_db
  autos_jlab:
    build:
      context: .
      dockerfile: ./DockerfileJlab
    container_name: "autos_jlab"
    env_file: .env
    environment:
      DEBUG: "1"
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: .
        target: /app
    command: jupyter lab --allow-root --no-browser --ip=0.0.0.0
    depends_on:
      - autos_db

volumes:
  autos_postgres_data:
